import { motion } from 'framer-motion';
import { Copy, Check, RefreshCw, Download, Share2 } from 'lucide-react';
import { useState } from 'react';
import toast from 'react-hot-toast';
import NewsSourceCard from './NewsSourceCard';
import QualityScore from './QualityScore';
import HashtagDisplay from './HashtagDisplay';
import ImageSuggestion from './ImageSuggestion';

const GeneratedPost = ({ data, onReset }) => {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const fullPost = `${data.linkedin_post}\n\n${data.hashtags?.join(' ') || ''}`;
    navigator.clipboard.writeText(fullPost);
    setCopied(true);
    toast.success('Copied to clipboard!');
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const content = `${data.linkedin_post}\n\n${data.hashtags?.join(' ') || ''}\n\nGenerated by AI LinkedIn Post Generator`;
    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `linkedin-post-${data.topic.replace(/\s+/g, '-').toLowerCase()}.txt`;
    a.click();
    toast.success('Downloaded!');
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="space-y-6"
    >
      {/* Main Post Card */}
      <div className="glass-card rounded-3xl p-8">
        <div className="flex items-start justify-between mb-6">
          <div>
            <h2 className="text-2xl font-bold text-slate-800 mb-2">
              Your LinkedIn Post ✨
            </h2>
            <p className="text-sm text-slate-500">
              Topic: <span className="font-semibold text-slate-700">{data.topic}</span>
            </p>
          </div>
          
          {data.quality_score && (
            <QualityScore score={data.quality_score} />
          )}
        </div>

        {/* Post Content */}
        <div className="bg-white/50 rounded-2xl p-6 mb-6 border-2 border-slate-100">
          <div className="prose prose-slate max-w-none">
            <pre className="whitespace-pre-wrap font-sans text-slate-700 leading-relaxed">
              {data.linkedin_post}
            </pre>
          </div>
        </div>

        {/* Hashtags */}
        {data.hashtags && data.hashtags.length > 0 && (
          <HashtagDisplay hashtags={data.hashtags} />
        )}

        {/* Stats */}
        <div className="flex flex-wrap gap-4 mb-6 text-sm">
          <div className="flex items-center gap-2 px-3 py-2 bg-blue-50 rounded-lg">
            <span className="text-blue-600 font-semibold">Words:</span>
            <span className="text-slate-700">{data.word_count}</span>
          </div>
          <div className="flex items-center gap-2 px-3 py-2 bg-purple-50 rounded-lg">
            <span className="text-purple-600 font-semibold">Characters:</span>
            <span className="text-slate-700">{data.character_count}</span>
          </div>
          {data.news_sources && (
            <div className="flex items-center gap-2 px-3 py-2 bg-green-50 rounded-lg">
              <span className="text-green-600 font-semibold">Sources:</span>
              <span className="text-slate-700">{data.news_sources.length}</span>
            </div>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex flex-wrap gap-3">
          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleCopy}
            className="flex items-center gap-2 px-6 py-3 bg-primary-600 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl transition-all"
          >
            {copied ? <Check className="w-5 h-5" /> : <Copy className="w-5 h-5" />}
            <span>{copied ? 'Copied!' : 'Copy Post'}</span>
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={handleDownload}
            className="flex items-center gap-2 px-6 py-3 bg-slate-600 text-white rounded-xl font-semibold shadow-lg hover:shadow-xl transition-all"
          >
            <Download className="w-5 h-5" />
            <span>Download</span>
          </motion.button>

          <motion.button
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={onReset}
            className="flex items-center gap-2 px-6 py-3 bg-white border-2 border-slate-300 text-slate-700 rounded-xl font-semibold hover:bg-slate-50 transition-all"
          >
            <RefreshCw className="w-5 h-5" />
            <span>Generate Another</span>
          </motion.button>
        </div>
      </div>

      {/* Image Suggestion */}
      {data.image_suggestion && (
        <ImageSuggestion suggestion={data.image_suggestion} />
      )}

      {/* News Sources */}
      {data.news_sources && data.news_sources.length > 0 && (
        <div className="glass-card rounded-3xl p-8">
          <h3 className="text-xl font-bold text-slate-800 mb-4">
            📰 News Sources Used
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {data.news_sources.map((source, index) => (
              <NewsSourceCard key={index} source={source} index={index} />
            ))}
          </div>
        </div>
      )}

      {/* Processing Metadata (if available from enhanced endpoint) */}
      {data.processing_metadata && (
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.3 }}
          className="glass-card rounded-3xl p-8"
        >
          <h3 className="text-xl font-bold text-slate-800 mb-4">
            🔬 Processing Insights
          </h3>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
            <div className="bg-blue-50 rounded-xl p-4">
              <div className="text-blue-600 font-semibold mb-1">Search Attempts</div>
              <div className="text-2xl font-bold text-slate-800">
                {data.processing_metadata.search_attempts || 1}
              </div>
            </div>
            <div className="bg-purple-50 rounded-xl p-4">
              <div className="text-purple-600 font-semibold mb-1">Generation Attempts</div>
              <div className="text-2xl font-bold text-slate-800">
                {data.processing_metadata.generation_attempts || 1}
              </div>
            </div>
            {data.processing_metadata.news_analysis && (
              <div className="bg-green-50 rounded-xl p-4">
                <div className="text-green-600 font-semibold mb-1">Sentiment</div>
                <div className="text-lg font-bold text-slate-800 capitalize">
                  {data.processing_metadata.news_analysis.sentiment}
                </div>
              </div>
            )}
            {data.processing_metadata.news_analysis && (
              <div className="bg-orange-50 rounded-xl p-4">
                <div className="text-orange-600 font-semibold mb-1">Trend</div>
                <div className="text-lg font-bold text-slate-800 capitalize">
                  {data.processing_metadata.news_analysis.trend_direction}
                </div>
              </div>
            )}
          </div>
        </motion.div>
      )}
    </motion.div>
  );
};

export default GeneratedPost;